Support python version >= 3.8 (#7)
tracetronic/testguide_report-generator pull request #8
Opened 2024-04-18 10:30 UTC by ErikRehmTT

closes #7

2024-04-18 13:38 UTC, ErikRehmTT commented
Python 3.13 is currently in alpha and scheduled to be released in October. I tried it inside the test matrix, but something crashed in cpython during poetry install. Removed it again, as its still half a year till release anyway.

2024-04-22 06:25 UTC, MartinGroscheTT requested changes

2024-04-22 06:25 UTC, MartinGroscheTT commented on config/license/allowlist.json
> +      "moduleCopyright": "Barry Warsaw and the contributors to the project",
i guess the [copyrights ](https://github.com/jaraco/skeleton/issues/78) were deleted within the source files?

2024-04-22 06:25 UTC, MartinGroscheTT commented on config/license/allowlist.json
> +      "moduleCopyright": "Copyright Jason R. Coombs",
No copyright information anymore. First contributor cannot set as responsible

2024-04-22 11:44 UTC, MartinGroscheTT approved these changes

2024-04-22 12:49 UTC, merged